### PR TITLE
fix(docs): default for revertOnSpill is true

### PR DESCRIPTION
**Pull request by pndewit**
See: https://github.com/michaelmalonenz/aurelia-dragula/blob/master/src/dragula-and-drop.js#L16

### CODE REVIEW

**Comment by michaelmalonenz** [comment]
Oh dear - it appears that I have two different deafults... I think this portion of the docs refers to here:
https://github.com/michaelmalonenz/aurelia-dragula/blob/master/src/options.js#L18

but the one you're talking about is on the `dragula-and-drop` Custom Element

**Comment by pndewit** [comment]
whoops!
If I am not mistaken I just tested it and it seems like my statement is getting precedence over yours lol. At least, I haven't configured any options myself and it is reverting on spill.

**Comment by pndewit** [comment]
The default in Dragula is false, what is your preferred outcome? true or false?
I can update the PR to instead of changing the documentation, change the default value. That would make it a breaking change though...

**Comment by michaelmalonenz** [comment]
crap.  I meant `true`  I am tired.

**Comment by pndewit** [comment]
Already thought so. Keep up the good work!
I was running into issues with the shown order with plain Dragula. It seemed that Dragula is sometimes still changing the shown order after the `drop` and `dragend` events were emitted (I found that out after using a breakpoint after a 20ms timeout). But I were not able to figure out why and could only reproduce it by drag 'n dropping really quickly, so hope that your module fixes it.

**Comment by michaelmalonenz** [comment]
I think this is likely the  changeset you're interested in:

https://github.com/michaelmalonenz/aurelia-dragula/compare/1cda77239a91967994db08c5f07f080b2b0f3878...77a6f73478045032713d10b21fab129d54ed3d97

unfortunately, that includes the builds for the 3 attempts it took me, but yeah - my dragula doesn't flicker, *if* you call the cancel with `forceIgnoreRevert` set to `true` (like in the customElement)

But if you're using my module, I suggest using it like I do in the example: https://github.com/michaelmalonenz/aurelia-dragula-example

**Comment by pndewit** [comment]
Might be yes, I'll see if I am able to reproduce the issue using `aurelia-dragula`. I based my implementation on that example project you linked (and created) yes. Thanks!

**Comment by michaelmalonenz** [comment]
The two sources of defaults now agree, and the documentation reflects that.  Fixed in v2.0.0

**Pull request closed without merging**
