### PR TITLE
Fixes "ReferenceError: _item is not defined" while dropping an element

### PR DESCRIPTION
**Pull request by cdennig**
Hi Michael,

here is another small fix...when you drag an element and drop it on a target (where e.g. source and target are the same `UL`), then a ReferenceException may occur, because you use `_item `instead of `this._item` or `item` (from the method parameters).
Unfortunately, I have no unit test for this at the moment...but I think it is a very small change, should be ok though.

Cheers,
Chris

### CODE REVIEW

**Comment by cdennig** [comment]
Uhh...hold on, it should be `this._copy`, no?

**Comment by michaelmalonenz** [comment]
Hmmm, good question.  The [original](https://github.com/bevacqua/dragula/blob/master/dragula.js#L251) suggests it should be `this._item` 

Though I suspect you've happened upon the cause of [this](https://github.com/bevacqua/dragula/issues/329)

I'm currently looking at writing a test to confirm it.

**Comment by cdennig** [comment]
If I use `this`, then the item is removed from the source...I guess that should not happen. If I use `this._copy` then the UI behaves as expected. Nevertheless, thanks for investigating...

Cheers,
Chris

**Comment by michaelmalonenz** [comment]
Ok.  So how sure are you that `this._item` shouldn't be removed from the DOM?  After going to a bunch of trouble to write some tests, I've discovered that `this._copy` is never even added to the DOM in the first place, so removing it is a noop.

Please take a look at [this commit](https://github.com/michaelmalonenz/aurelia-dragula/commit/fd7784f9db2c9bbb7e2d21ba19730a6e4eec896e) and tell me what you think.

I've left it as removing `this._item` but I don't know if this is ideal behaviour - sorry, I've never used the `copy` / `copySortSource` options which seems a little bad, given that I've released this thing... though it is a fork!

**Comment by cdennig** [comment]
See my comment on your commit. I'll close this one...

Cheers,
Chris

**Pull request closed without merging**
